### ISSUE TITLE
Info about upcoming removal of packages in the General registry

### ISSUE THREAD

**Issue by KristofferC** [MatlabCompat/MatlabCompat.jl#17]
As described in https://discourse.julialang.org/t/ann-plans-for-removing-packages-that-do-not-yet-support-1-0-from-the-general-registry/ we are planning on removing packages that do not support 1.0 from the General registry. This package has been detected to not support 1.0 and is thus slated to be removed. The removal of packages from the registry will happen approximately a month after this issue is open.

To transition to the new Pkg system using `Project.toml`, see https://github.com/JuliaRegistries/Registrator.jl#transitioning-from-require-to-projecttoml.
To then tag a new version of the package, see https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app.

If you believe this package has erroneously been detected as not supporting 1.0 or have any other questions, don't hesitate to discuss it here or in the thread linked at the top of this post.

**Comment by aminya** [comment]
I am working on a much more comprehensive package in my [JuliaMatlab](https://github.com/juliamatlab) organization. 
So far MatLang is under developement:
https://github.com/juliamatlab/MatLang

So I think my packages will replace this repository.

**Comment by ayakimovich** [comment]
Dear @aminya and @KristofferC it seems that's there's an overlapping effort towards the direction MatlabCompat.jl was going. @aminya I do remember your pull requests some time ago. Unfortunately, I wasn't able to reply timely enough. MatlabCompat was aimed as group effort and is created as github organisation. I am happy to add / pass on the contributor/admin privileges to new members who are interested.

**Comment by aminya** [comment]
@ayakimovich I decided to start up my own [organization and sets of packages](https://github.com/juliamatlab) organization. Because MatlabCompat is written for Julia 0.4 and updating it is like writing almost everything from the ground up, and the process is not straight forward too.
I abandoned and closed that pull request because it wasn't complete. 

If you like you can join me in JuliaMatlab and help developing.
